pretrained_model_path: "./stable-diffusion-v1-4"
root_path: "./modelscope/text-to-video"

train_data:
  name: object_tracking
  path: "./dataset"
  datasets:
    - "got10k"
    - "youvis"
  n_sample_frames: 8 
  width: 256
  height: 256
  split: "train"
  num_max_obj: 8


seed: 33
mixed_precision: fp16
enable_xformers_memory_efficient_attention: True

# the root path refers to the pretrained model-scope text to video folder , you can download it from https://huggingface.co/ali-vilab/modelscope-damo-text-to-video-synthesis/tree/main
